# -*- coding: utf-8 -*-
"""Tredence Analytics_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SV9Hqv_SaYO-f_czt_r23n4o7tFHMzI8
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#DATA

# First we normalize the image
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])

train_dataset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform)

test_dataset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform)

# Split the data into train + validation
train_size = int(0.9 * len(train_dataset))
val_size = len(train_dataset) - train_size

train_dataset, val_dataset = torch.utils.data.random_split(
    train_dataset, [train_size, val_size])

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=128, shuffle=True)
val_loader   = torch.utils.data.DataLoader(val_dataset, batch_size=128, shuffle=False)
test_loader  = torch.utils.data.DataLoader(test_dataset, batch_size=128, shuffle=False)

# PRUNABLE LAYER
class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        # Weight and Bias
        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias   = nn.Parameter(torch.zeros(out_features))

        # Gate para
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features))
        self.temperature = 10.0   # STRONG pruning

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores * self.temperature)
        pruned_weights = self.weight * gates # Element wise multiplication
        return F.linear(x, pruned_weights, self.bias)

# MODEL

class Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        # Prunable FC layers
        self.fc1 = PrunableLinear(128*4*4, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x



#  SPARSITY LOSS
def sparsity_loss(model):
    loss, total = 0, 0
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates = torch.sigmoid(m.gate_scores * m.temperature)
            loss += gates.sum()
            total += gates.numel()
    return loss / (total + 1e-8) #Normalized

# Calculate Sparsity %

def calculate_sparsity(model, threshold=1e-2):
    total, zero = 0, 0
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates = torch.sigmoid(m.gate_scores * m.temperature)
            total += gates.numel()
            zero += (gates < threshold).sum().item()
    return 100 * zero / total

# HARD PRUNING

def apply_pruning(model, threshold=1e-2):
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates = torch.sigmoid(m.gate_scores * m.temperature)
            mask = (gates > threshold).float()
            m.weight.data *= mask

# EVAL
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            _, pred = torch.max(out, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    return 100 * correct / total

# TRAIN

def train_model(lambda_, epochs=15):
    model = Net().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs, eta_min=1e-4)

    warmup_epochs = 5

    print(f"\n==== Training λ = {lambda_} ====")

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for x, y in train_loader:
            x, y = x.to(device), y.to(device)

            out = model(x)
            ce_loss = F.cross_entropy(out, y) #Cross-entropy Loss

            # λ annealing - Apply sparsity only after warmup training
            if epoch < warmup_epochs:
                current_lambda = 0
            else:
                progress = (epoch - warmup_epochs) / (epochs - warmup_epochs)
                current_lambda = lambda_

            sp_loss = sparsity_loss(model)

            # Total Loss
            loss = ce_loss + current_lambda * sp_loss * 5

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()

            total_loss += loss.item()

        scheduler.step()

        # Now Evaluate on Validation set
        acc = evaluate(model, val_loader)
        sp  = calculate_sparsity(model)

        print(f"Epoch {epoch+1}/{epochs} | Acc {acc:.2f}% | Sparsity {sp:.2f}%")

    apply_pruning(model)

    final_acc = evaluate(model, test_loader)
    final_sp  = calculate_sparsity(model)

    print(f"\nFinal Accuracy: {final_acc:.2f}% | Sparsity: {final_sp:.2f}%")

    return final_acc, final_sp, model

# RUN

results = []

for lam in [0.1, 1, 5, 10, 20]:
    acc, sp, model = train_model(lam)
    results.append((lam, acc, sp))

print("\nFINAL RESULTS:")
def print_results_table(results):
    print("\nFinal Results Table\n")
    print(f"{'Lambda(λ)':<10} {'Test Accuracy (%)':<20} {'Sparsity (%)':<15}")
    print("-" * 50)

    for lam, acc, sp in results:
        print(f"{lam:<10} {acc:<20.2f} {sp:<15.2f}")
print_results_table(results)

def plot_gate_distribution(model, filename="gate_distribution.png"):
    all_gates = []

    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates = torch.sigmoid(m.gate_scores * m.temperature)
            all_gates.extend(gates.detach().cpu().numpy().flatten())

    plt.figure()
    plt.hist(all_gates, bins=50)
    plt.title("Distribution of Gate Values")
    plt.xlabel("Gate Value")
    plt.ylabel("Frequency")

    plt.savefig(filename)   # SAVE IMAGE
    plt.show()

plot_gate_distribution(model)   # use BEST model (λ=20)

"""## Gate Value Distribution

The histogram of gate values for the best model shows:

* A large spike at 0 → indicating many pruned connections.
* A smaller cluster near 1 → representing important active connections.

This bimodal distribution confirms that the network successfully learned to prune itself.**bold text**
"""

def plot_accuracy_vs_sparsity(results):
    sparsity = [r[2] for r in results]
    accuracy = [r[1] for r in results]

    plt.figure()
    plt.plot(sparsity, accuracy, marker='o')
    plt.xlabel("Sparsity (%)")
    plt.ylabel("Accuracy (%)")
    plt.title("Accuracy vs Sparsity Trade-off")
    plt.grid()
    plt.show()

plot_accuracy_vs_sparsity(results)

def plot_lambda_vs_metrics(results):
    lambdas  = [r[0] for r in results]
    accuracy = [r[1] for r in results]
    sparsity = [r[2] for r in results]

    plt.figure()
    plt.plot(lambdas, accuracy, marker='o', label="Accuracy")
    plt.plot(lambdas, sparsity, marker='s', label="Sparsity")
    plt.xlabel("Lambda")
    plt.ylabel("Value")
    plt.title("Lambda vs Accuracy and Sparsity")
    plt.legend()
    plt.grid()
    plt.show()

plot_lambda_vs_metrics(results)

"""# 📌 Self-Pruning Neural Network – Report

## 🔹  Why L1 Penalty on Sigmoid Gates Encourages Sparsity?

The L1 penalty adds a cost proportional to the value of each gate, which pushes many gate values toward zero during training.

Important weights contribute significantly to the model’s predictions, so reducing their gate values would increase the classification loss. Because of this, they resist being pushed to zero and remain active.

On the other hand, weights that have little impact on the output can be reduced without hurting performance, so the L1 penalty dominates and make their gate values close to zero.

As a result, the network naturally keeps only the important connections and prunes away the unnecessary ones, leading to a sparse model.

---

## 🔹 Total Loss Function

The model is trained using the following objective:

$$\mathrm{Total\ Loss}=\mathrm{Classification\ Loss}+\lambda\cdot\mathrm{Sparsity\ Loss}$$

where:

* Classification Loss helps the model improve prediction accuracy
* Sparsity Loss encourages the network to remove unnecessary connections
* λ controls the tradeoff between accuracy and sparsity
---
##  Results: Effect of λ on Accuracy and Sparsity

| Lambda | Test Accuracy (%) | Sparsity (%) |
| ------ | ----------------- | ------------ |
| 0.1    | 80.07             | 51.03        |
| 1.0    | 79.53             | 59.93        |
| 5.0    | 79.24             | 72.21        |
| 10.0   | 78.87             | 79.71        |
| 20.0   | 78.66             | 85.61        |       

---
## 🔹 Observations

* Increasing λ increases sparsity in the network.
* This demonstrates the trade-off between model compression and predictive performance.

---

## 🔹Gate Value Distribution

The histogram of gate values for the best model shows:

* A large spike at 0 → indicating many pruned connections.
* A smaller cluster near 1 → representing important active connections.

This bimodal distribution confirms that the network successfully learned to prune itself.

---

## 🔹 Conclusion

The self-pruning mechanism effectively reduces the number of active parameters while maintaining high accuracy. This demonstrates that neural networks are highly overparameterized and can be significantly compressed without major performance loss.

The experiment successfully shows how L1 regularization on learnable gates can enable dynamic, data-driven pruning during training.

"""